site_name: Kometa Blog
site_author: meisnate12
site_description: The latest news from the Kometa team!
site_url: https://blog.kometa.wiki
repo_name: Kometa
repo_url: https://github.com/Kometa-Team/Kometa

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/icon.png
  favicon: assets/favicon.png
  font:
    text: Open Sans
    code: Fira Code
  features:
    - navigation.instant
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - navigation.tabs
    - navigation.expand
    - navigation.tracking
    - navigation.path
    - toc.follow
  language: en
  palette:
    scheme: slate

plugins:
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - Announcements
        - Hotfix
        - Showcase
        - Overlays
        - Collections
        - Playlists
        - Builders
        - Defaults
        - Guides
  - search:
      lang: en
  - include-markdown
  - tags
  - blog:
      enabled: true
      post_date_format: long
      post_dir: "{blog}/posts"
      blog_toc: true
      categories_toc: true
      blog_dir: .
      archive: false
      categories_allowed:
        - Announcements
        - Hotfix
        - Showcase
        - Overlays
        - Collections
        - Playlists
        - Builders
        - Defaults
        - Guides
extra:
  social:
    - icon: fontawesome/solid/heart
      class: md-social__link heart
      link: 'https://github.com/sponsors/meisnate12'
      name: Donate
    - icon: fontawesome/brands/discord
      class: md-social__link
      link: 'https://kometa.wiki/en/latest/discord/'
      name: Discord
    - icon: fontawesome/brands/github
      class: md-social__link
      link: 'https://github.com/Kometa-Team/Kometa'
      name: GitHub
copyright: Copyright &copy; 2024 meisnate12
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - neoteroi.cards
extra_css:
  - stylesheets/extra.css

nav:
  - Kometa Blog:
      - Latest News: index.md
  - Categories:
      - category/announcements


